select * from customer_shopping_behavior limit 50;
-- total revenue generated by male vs. female customers
select gender, sum(purchase_amount) as Total_revenue
from customer_shopping_behavior
group by gender;

-- customers used a discount but still spent more than the average purchase amount
select customer_id,purchase_amount
from  customer_shopping_behavior 
where discount_applied="YES" and 
purchase_amount >=(select avg(purchase_amount) from customer_shopping_behavior);

--  top 5 products with the highest average review rating
select item_purchased,round(AVG(review_rating),2) as avg_rating
from customer_shopping_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Comparing the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg(purchase_amount),2) as avg_purchase_amount
from customer_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type;

/* Do subscribed customers spend more? Compare average spend and total revenue 
between subscribers and non-subscribers */
select subscription_status, count(customer_id) as No_of_Customers,
round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as total_spend
from customer_shopping_behavior
group by subscription_status;    -- Non_subscribers spending more than subscribers

-- which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round((sum(case when discount_applied='Yes' then 1 else 0 end)/count(*))*100,2) as percentage_of_purchases
from customer_shopping_behavior
group by item_purchased
order by percentage_of_purchases desc limit 5;

/* Segment customers into New, Returning and Loyal based on their total number
 of previous purchases, and show the count of each segment */
 -- without cte
select
case
when previous_purchases=1 then "New"
when previous_purchases>= 2 and previous_purchases<=10 then "Returning"
else "Loyal"
end as segment,
count(case
when previous_purchases=1 then "New"
when previous_purchases>= 2 and previous_purchases<=10 then "Returning"
else "Loyal"
 end) as segment_count
 from customer_shopping_behavior
 group by segment;
 
 -- with cte
with cte as(
select customer_id,previous_purchases,
case
when previous_purchases=1 then "New"
when previous_purchases>= 2 and previous_purchases<=10 then "Returning"
else "Loyal"
end as segment from customer_shopping_behavior)
select segment,count(*) as segment_count
from cte
group by segment;

-- top 3 most purchased products within each category?
with cte as(
select category, item_purchased,count(item_purchased) as purchased_count,
row_number() over (partition by category order by count(item_purchased) desc)as rank_of_item
 from customer_shopping_behavior
 group by category, item_purchased)
select rank_of_item,category,item_purchased,purchased_count from cte
where rank_of_item<=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_customers
from customer_shopping_behavior
where previous_purchases>5
group by subscription_status;

-- revenue contribution of each age group

select age_group, sum(purchase_amount) as revenue
from customer_shopping_behavior
group by age_group
order by sum(purchase_amount) desc
 
 

